config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'
  resources :blogs do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show]
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :blog, counter_cache: :likes_count
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]

  def index
    @blogs = Blog.includes(:user).all.order('created_at DESC')
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(text: blog_params[:text], user_id: current_user.id)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  private
  def blog_params
    params.permit(:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, blog_id: params[:blog_id])
    @likes = Like.where(blog_id: params[:blog_id])
    @blogs = Blog.all
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, blog_id: params[:blog_id])
    like.destroy
    @likes = Like.find(id: params[:id])
    @blogs = Blog.all

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @blogs = current_user.blogs.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
 <div class="col s12 m7">
    <div class="card horizontal">
      <div class="card-image">
      </div>
      <div class="card-stacked">
        <div class="card-content">
           <%= simple_format(blog.text) %>
        </div>
        <div class="card-action">
          <%= link_to 'SHOW', "/blogs/#{blog.id}", method: :get %>
          <% if user_signed_in? && current_user.id == blog.user_id %>
          <%= link_to 'EDIT', "/blogs/#{blog.id}/edit", method: :get %>
          <%= link_to 'DESTROY', "/blogs/#{blog.id}", method: :delete %>
          <% end %>
          <%= render partial: 'likes/like', locals: { blog: blog } %>
        </div>
      </div>
    </div>
  </div>

app/views/blogs/create.html.erb
<div class="contents row">
  <div class="success">
    <h5>
      投稿が完了しました。
    </h5>
    <a class="btn" href="/blogs">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/destroy.html.erb
 <div class="contents row">
    <div class="success">
      <h5>
        削除が完了しました。
      </h5>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/blogs/edit.html.erb
<div class="contents row">
    <%= form_for @blog, url: "/blogs/#{@blog.id}",method: :patch do |f| %>
      <h5>
        Edit
      </h5>
      <textarea cols="30" name="text" placeholder="text" rows="30"><%= @blog.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>

app/views/blogs/index.html.erb
<div class="contents row">
  <% @blogs.each do |blog| %>
    <%= render partial: "blog", locals: { blog: blog } %>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div class="row">
  <%= form_for @blog do |f| %>
    <form class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <textarea id="textarea1" class="materialize-textarea" name="text"></textarea>
          <label for="textarea1">本文</label>
        </div>
        <input type="submit" value="送信">
      </div>
    </form>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class="contents row">
  <div class="col s12 m7">
    <div class="card horizontal">
      <div class="card-image">
      </div>
      <div class="card-stacked">
        <div class="card-content">
           <%= simple_format(@blog.text) %>
        </div>
        <div class="card-action">
          <a href="#">SHOW</a>
          <% if user_signed_in? && current_user.id == @blog.user_id %>
          <%= link_to 'EDIT', "/blogs/#{@blog.id}/edit", method: :get %>
          <%= link_to 'DESTROY', "/blogs/#{@blog.id}", method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/update.html.erb
 <div class="contents row">
    <div class="success">
      <h5>
        更新が完了しました。
      </h5>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miniappli</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style type="text/css" href="./style.css"></style>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

</head>
<body>

   <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Blog</a>
      <% if user_signed_in? %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
        <a href="/users/<%= current_user.id %>">MyPage</a></li>
        <li><%= link_to "SignOut", destroy_user_session_path, method: :delete %></li>
        <li><a class="post" href="/blogs/new">New</a></li>
      </ul>
      <% else %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "LogIn", new_user_session_path, class: 'post' %></li>
        <li><%= link_to "SingIn", new_user_registration_path, class: 'post' %></li>
      </ul>
      <% end %>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/likes/_like.html.erb
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<% if user_signed_in? %>

  <% if blog.like_user(current_user.id) %>
  <%= button_to blog_like_path(id: blog.likes.ids, blog_id: blog.id), method: :delete, id: "like-buttons", remote: true do %>
    <i class="material-icons">favorite</i>
      <span>
        <%= blog.likes_count %>
      </span>
    <% end %>

  <% else %>
    <%= button_to blog_likes_path(blog), id: "like-buttons", remote: true do %>
    <i class="material-icons">favorite_border</i>
      <span>
        <%= blog.likes_count %>
      </span>
    <% end %>
  <% end %>


<% else %>
  <i class="material-icons">favorite_border</i>
    <span>
      <%= blog.likes_count %>
    </span>
<% end %>

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { blogs: @blogs, blog: @blog, likes: @likes, like: @like}) %>")

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { blogs: @blogs, blog: @blog, likes: @likes}) %>");

app/views/users/show.html.erb
<div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @blogs.each do |blog| %>
      <%= render partial: "blogs/blog", locals: { blog: blog } %>
    <% end %>
  </div>